name: PHP 7.4 CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Check Version
        run: php -v