name: My First Pipeline

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "CI/CD Working"

      - name: Read File
        run: cat hello.txt